[server]
address = "0.0.0.0:8000"
location = "Asia/Singapore"
baseLogPath = "./log"
serverName = "quant"
serviceName = "all"
serverTag = "main"

[baseLog]
fileName = "info.log"
fileMaxSize = 500
FileMaxBackups = 10
FileMaxAge = 10

[dataLog]
fileName = "data.log"
fileMaxSize = 500
FileMaxBackups = 10
FileMaxAge = 10

[redis]
address = "172.31.177.158:6379"
password = "foobared"
maxActive = 10
maxIdle = 5
idleMills = 0

[mysql]
user = "slagga"
password = "slagga"
address = "172.31.177.158:3306"
dataBase = "exchange_quant"
maxOpenConn = 10
maxIdleConn = 3

[trade]
endpoint = "https://testnet.okex.com"
wsEndpoint = "wss://real.okex.com:8443/ws/v3?brokerId=181"
apiKey = "666cd148-9cb1-4a0d-a343-e7be2d1e666f"
secretKey = "0B95195A625F490452344CAD24E663E0"
passphrase = "slagga"
timeoutSecond = 10
isPrint = true
i18n = "en_US"
tradePwd = "f4bf0913e77fc631c8faab17076ce259"   #test1

[service]
notifyUrl = "http://172.31.177.157:8001"
